#!/bin/bash
dir="`zenity --file-selection --title="Выбор папки с игрой" --directory `" 
if [[ "${dir}" == "" ]]
then
exit 0
fi
e="`echo ${dir} | sed "s/ /_/g"`"
name="`basename ${e}`"
opts=" -comp lz4 -Xhc"
mksquashfs "${dir}" "`cat ~/gamesdir`/${name}.fs" ${opts}
#ln -s "${dir}/${name}.fs" "`cat ~/gamesdir`/${name}.fs"
mkdir "`cat ~/gamesdir`/${name}" "`cat ~/gamesdir`/layers/${name}" "`cat ~/gamesdir`/layers/${name}"/{data,work,up}
echo "${name} `zenity --entry --title="Параметры игры" --text="Изолированное окружение (1\0)"` \
`zenity --entry --title="Параметры игры" --text="Имя исполняемогого файла и скрипта"`" >> \
"`cat ~/gamesdir`/envs/game-list"
if ! zenity --question --title="Сторонние библиотеки" --text=" Сторонние библиотеки в папке с игрой отсутствуют"
then
echo "`zenity --entry --title="библиотеки игры" --text="путь к внутренним библиотекам"`" > "`cat ~/gamesdir`/envs/LIB_${name}"
fi

