#!/bin/bash
#VERESION=Y003
mounter=/usr/bin/mounter
if [ -f "/home/${USER}/gamesdir" ]
	then
	gamesdir=`cat /home/${USER}/gamesdir` # место размещения файлов
	else
	dist=$(echo -n $(zenity --entry \
	--title="Первый запуск" \
	--text="Введите абсолютный путь к папке где будут размещатся игры" ))
	echo $dist > /home/${USER}/gamesdir
	mkdir -p $dist $dist/envs $dist/layers
	touch $dist/envs/game-list
	echo "export Jprofile='--noprofile'" >> $dist/envs/conf
	echo "export Jnet='--net=none'" >> $dist/envs/conf
	exit 0
fi
gamesdir="`cat /home/${USER}/gamesdir`"
cd ${gamesdir}
echo 1
`cat envs/conf`
runjailed (){
if [ ${JAIL} == 1  ];
    then
    firejail ${Jprofile} ${Jnet} \
    $1
    else
    $1
fi
}
echo 2	
if ! cat envs/game-list | awk ' {print $1} ' | grep "$@"  # запуск выбраной игры напрямую run-games $game-name
    then
	echo "2.5"
        sel=$(echo -n $(zenity --list \
        --width=600 --height=400 \
        --title="Выбери игру" \
        --column="Игры" \
        `cat envs/game-list | awk ' {print $1} '` \
        "Добавить игру"))
    else
    sel=$@
fi
echo ${sel}
if [[ ${sel} == "Добавить игру" ]]
then 
gamepacker
exit 0
fi
echo 3
if ! cat envs/game-list | awk ' {print $1} ' | grep $sel
then
exit 0
fi
echo 4
game_name=` grep $sel envs/game-list | awk ' {print $1} '`
JAIL=` grep $sel envs/game-list | awk ' {print $2} '`
game_bin=` grep $sel envs/game-list | awk ' {print $3} '`
game_run=${game_bin}
z=`grep $sel envs/game-list | awk ' {print $4} '`
if test "$z" != ""
	then
	game_run=`grep $sel envs/game-list | awk ' {print $4} '`
fi
echo 5

export LD_LIBRARY_PATH="`cat envs/LIB_${game_name} `:${LD_LIBRARY_PATH}"


sudo ${mounter} ${game_name} m ${gamesdir}
cd ${game_name}
echo ${game_bin} " "   ${game_run} " " ${game_name}
echo 6

if ! ldd ${game_bin} | grep "not found"  
	then
	runjailed "./${game_run}"
	else
	sudo ${mounter} steam-runtime m ${gamesdir}
	find  ../steam-runtime \( -name "libgcc_s.so*" -o -name "libstdc++.so*" -o -name "libxcb.so*" -o -name "libgpg-error.so*" \) -print -delete
	runjailed "../steam-runtime/run.sh ./${game_run}"
	cd ${gamesdir}
	sudo ${mounter} steam-runtime u ${gamesdir}
fi
echo 7
cd ${gamesdir}
sudo ${mounter} ${game_name} u ${gamesdir}

