#!/bin/bash
#VERESION=Z001
#export mesa_glthread=true
#export GALLIUM_HUD=fps
#export MESA_GL_VERSION_OVERRIDE=4.1 MESA_GLSL_VERSION_OVERRIDE=410
#export vblank_mode=0
mounter=/usr/bin/mounter
JAIL=0

runjailed (){
if [ ${JAIL} == 1  ];
    then
    firejail --profile="~/.config/firejail/firejail.profile" --net=none \
    $1
    else
    $1
fi
}

if [ -f "~/gamesdir" ]
	then
	gamesdir=`cat ~/gamesdir` # место размещения файлов
	else
	dist=$(echo -n $(zenity --entry \
	--title="Первый запуск" \
	--text="Введите путь к папке где будут размещатся игры" ))
	echo $dist > ~/gamesdir
	mkdir -p $dist $dist/envs $dist/layers
	touch $dist/envs/game-list
fi
	


cd ${gamesdir}
if ! cat envs/game-list | awk ' {print $1} ' | grep $@  # запуск выбраной игры напрямую run-games $game-name
    then
        sel=$(echo -n $(zenity --list \
        --title="Выбери игру" \
        --column="Игры" \
        `cat envs/game-list | awk ' {print $1} '`))
    else
    sel=$@
fi
game_name=` grep $sel envs/game-list | awk ' {print $1} '`
game_bin=` grep $sel envs/game-list | awk ' {print $2} '`
game_run=${game_bin}
z=`grep $sel envs/game-list | awk ' {print $3} '`
if test "$z" != ""
	then
	game_run=`grep $sel envs/game-list | awk ' {print $3} '`
fi


export LD_LIBRARY_PATH="`cat envs/LIB_${game_name} `:${LD_LIBRARY_PATH}"


sudo ${mounter} ${game_name} m
cd ${game_name}
echo ${game_bin} " "   ${game_run} " " ${game_name}


if ! ldd ${game_bin} | grep "not found"  
	then
	runjailed "./${game_run}"
	else
	sudo ${mounter} steam-runtime m
	find  ../steam-runtime \( -name "libgcc_s.so*" -o -name "libstdc++.so*" -o -name "libxcb.so*" -o -name "libgpg-error.so*" \) -print -delete
	runjailed "../steam-runtime/run.sh ./${game_run}"
	cd ${gamesdir}
	sudo ${mounter} steam-runtime u
fi
cd ${gamesdir}
sudo ${mounter} ${game_name} u



